### ISSUE TITLE
QLMobi is not available via Homebrew

### ISSUE THREAD

**Issue by Jon-Schneider** [bfabiszewski/QLMobi#2]
It would be convenient to be able to automatically install QLMobi via Homebrew rather than something like this: 

```bash
cd "Downloads"
curl -fsSL -o QLMobi.zip $(curl https://api.github.com/repos/bfabiszewski/QLMobi/releases | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
unzip QLMobi.zip
cp -R QLMobi.qlgenerator ~/Library/QuickLook
```

Another QL Plugin, QLMarkdown (https://github.com/toland/qlmarkdown) is, so it's technically possible.

**Comment by bfabiszewski** [comment]
Thanks for the idea!

I don't use homebrew and don't have any idea how to implement this. 
When I find time I'll have a look at it.

In the meantime, if anyone wants to create a homebrew cask for the plugin I'll be glad to add it to install instructions.

**Comment by Jon-Schneider** [comment]
It doesn't look like it should be all that hard, though they prefer the official maintainers do it to get in the main repository - here's the Cask entry for QLMarkdown:

https://github.com/caskroom/homebrew-cask/blob/master/Casks/qlmarkdown.rb
```ruby
cask 'qlmarkdown' do
  version '1.3.5'
  sha256 'a290edf5b6124cbd4e526217e0979a9011c8ef3b964a33458f5063d51a9b15f2'

  url "https://github.com/toland/qlmarkdown/releases/download/v#{version}/QLMarkdown.qlgenerator.zip"
  appcast 'https://github.com/toland/qlmarkdown/releases.atom',
          checkpoint: '90c2dd6a28f257f169c067ad0f8b24b42cf0edd38955bfe0e629215cf8db74f7'
  name 'QLMarkdown'
  homepage 'https://github.com/toland/qlmarkdown'

  qlplugin 'QLMarkdown.qlgenerator'
end
```

**Comment by Jon-Schneider** [comment]
For the current version of QLMobi that would be:

```ruby
cask 'qlmobi' do
  version '0.5'
  sha256 '1035181685c3ed974bd45ade8f22717c62142ff6a75cf679128f8fb50ef26833'

  url 'https://github.com/bfabiszewski/QLMobi/releases/download/v0.5/QLMobi.qlgenerator.zip'
  appcast 'https://github.com/bfabiszewski/QLMobi/releases.atom',
          checkpoint: '6411eb86a26c0912d9f2213d3d20bddb7a9a351d3c15d507dab4e71576ea2c85'
  name 'QLMobi'
  homepage 'https://github.com/bfabiszewski/QLMobi'

  qlplugin 'QLMobi.qlgenerator'
end
```

I used ```shasum -a 256 [zip file]``` to calculate the checksum, verifying that using the command on the QLMarkdown zip matched the formula hash.

**Comment by bfabiszewski** [comment]
Thanks a lot! 

I rechecked the sha hashes and everything seems fine. I would only use ```#{version}``` variable in ```url``` instead of hardcoding version number (as in qlmarkdown example).

The pull request requires a number of checks before submitting:
 - [ ] ```brew cask audit --download {{cask_file}}``` is error-free.
  - [ ] ```brew cask style --fix {{cask_file}}``` reports no offenses.
 - [ ] ```brew cask install {{cask_file}}``` worked successfully.
  - [ ] ```brew cask uninstall {{cask_file}}``` worked successfully.

As I don't have ```brew``` I can't test it. Did you actually run those checks?

**Comment by Jon-Schneider** [comment]
I just did, with no problems.

Here's the final code - it now uses the version variable in the download url:

```ruby
cask 'qlmobi' do
  version '0.5'
  sha256 '1035181685c3ed974bd45ade8f22717c62142ff6a75cf679128f8fb50ef26833'

  url "https://github.com/bfabiszewski/QLMobi/releases/download/v#{version}/QLMobi.qlgenerator.zip"
  appcast 'https://github.com/bfabiszewski/QLMobi/releases.atom',
          checkpoint: '6411eb86a26c0912d9f2213d3d20bddb7a9a351d3c15d507dab4e71576ea2c85'
  name 'QLMobi'
  homepage 'https://github.com/bfabiszewski/QLMobi'

  qlplugin 'QLMobi.qlgenerator'
end
```

**Comment by Jon-Schneider** [comment]
Here's a fork with the added Cask: https://github.com/Jon-Schneider/homebrew-cask/blob/add-qlmobi/Casks/qlmobi.rb

**Comment by Jon-Schneider** [comment]
Here's a fork with the cask added: https://github.com/Jon-Schneider/homebrew-cask/blob/add-qlmobi/Casks/qlmobi.rb. I can make the PR if you want.

**Comment by bfabiszewski** [comment]
Great! 
Sure, go ahead with pull request.

**Comment by Jon-Schneider** [comment]
PR: https://github.com/caskroom/homebrew-cask/pull/30157

**Comment by bfabiszewski** [comment]
Jon, thanks a lot for taking care of this!

**Comment by Jon-Schneider** [comment]
Cask is Merged.
