### ISSUE TITLE
Does not seem to work on Big Sur

### ISSUE THREAD

**Issue by DataGreed** [bfabiszewski/QLMobi#7]
I've installed the plugin on Big Sur using `brew install --cask qlmobi` , tried reloading the db with `qlmanage -r` but it didn't help.

Here's the output of `qlmanage -d 4 -p -o /tmp /path/to/your/test.mobi`:

```
~ % qlmanage -d 4 -p -o /tmp /path/to/your/test.mobi
qlmanage: illegal option -- 
Usage: qlmanage [OPTIONS] path...
	-h		Display this help
	-r		Force reloading Generators list
	-r cache	Reset thumbnail disk cache
	-m [name ...]	Display statistics about quicklookd. Stats names:
			* plugins	Show the generators list
			* server	Show quicklookd life information
			* memory	Show quicklookd memory consumption
			* burst		Show statistics about the last burst
			* threads	Show concurrent accesses stats
			* other		Show other information about quicklookd
	-p		Compute previews of the documents
	-t		Compute thumbnails of the documents
	-x		Use quicklookd (remote computation)
	-i		Compute thumbnail in icon mode
	-s size		Size for the thumbnail
	-f factor	Scale factor for the thumbnail
	-F factor	Scale factor for the thumbnail, draw downscaled and compare to 1x
	-z		Display generation performance info (don't display thumbnails)
	-o dir		Output result in dir (don't display thumbnails or previews)
	-c contentType	Force the content type used for the documents
	-g generator	Force the generator to use
```

**Comment by bfabiszewski** [comment]
There is problem with Quick Look plugins on newer versions of macOS. I have myself problems with some plugins. They usually start working after multiple tries, but there is no single common solution to the problem. One of the issues is that the plugins are no officially signed.
See for example this discussion on QLStephen plugin support page: https://github.com/whomwah/qlstephen/issues/81 or https://github.com/whomwah/qlstephen/issues/112

BTW. It seems that Apple changed qlmanage options. On your system you should rather use it without `-d` argument:
`~ % qlmanage -p -o /tmp /path/to/your/test.mobi`

**Comment by bfabiszewski** [comment]
Do you have Apple M1 CPU?

**Comment by DataGreed** [comment]
Thank you for the reply!

> Do you have Apple M1 CPU?

no, I am on still on intel.

It's weird - I've reinstalled it a couple of times and it suddenly started working 😅

**Comment by bfabiszewski** [comment]
This is really unpredictable.
Nice that you managed to make it work
