### ISSUE TITLE
Doesn't work on Sonoma 14.2.1

### ISSUE THREAD

**Issue by steveparry1** [bfabiszewski/QLMobi#9]
Using a MBPro M1 running Sonoma 14.2.1  _ ran the terminal command you suggested and I got this: 

Last login: Fri Feb  2 20:33:18 on console
steveparry@Julay1 ~ % qlmanage -d 4 -p -o /tmp /path/to/your/test.mobi
qlmanage: illegal option -- 
Usage: qlmanage [OPTIONS] path...
	-h		Display this help
	-r		Force reloading Generators list
	-r cache	Reset thumbnail disk cache
	-m [name ...]	Display statistics about quicklookd. Stats names:
			* plugins	Show the generators list
			* server	Show quicklookd life information
			* memory	Show quicklookd memory consumption
			* burst		Show statistics about the last burst
			* threads	Show concurrent accesses stats
			* other		Show other information about quicklookd
	-p		Compute previews of the documents
	-t		Compute thumbnails of the documents
	-x		Use quicklookd (remote computation)
	-i		Compute thumbnail in icon mode
	-s size		Size for the thumbnail
	-f factor	Scale factor for the thumbnail
	-F factor	Scale factor for the thumbnail, draw downscaled and compare to 1x
	-z		Display generation performance info (don't display thumbnails)
	-o dir		Output result in dir (don't display thumbnails or previews)
	-c contentType	Force the content type used for the documents
	-g generator	Force the generator to use

steveparry@Julay1 ~ %

**Comment by bfabiszewski** [comment]
It seems they dropped `-d` option in newer `qlmanage` versions. Just remove `-d 4` from the command.

**Comment by steveparry1** [comment]
Now I get this:

Last login: Fri Feb  2 21:00:24 on ttys000
steveparry@Julay1 ~ % qlmanage -p -o /tmp /path/to/your/test.mobi
Testing Quick Look preview with files:
	/path/to/your/test.mobi
* /path/to/your/test.mobi did not produce any preview
steveparry@Julay1 ~ %

**Comment by bfabiszewski** [comment]
Do you realize you have to change `/path/to/your/test.mobi` to a real path to the file you want to test?

**Comment by steveparry1** [comment]
No - I am a complete beginner in using the Terminal or Console. I don't know how I should paste the appropriate text in. I'd be grateful if you could explain how to copy the path to my file in to the text.

**Comment by bfabiszewski** [comment]
Write `qlmanage -p -o /tmp ` and then paste any mobi file into the console. It will be converted to its path. Or even better drag the file into console.

**Comment by steveparry1** [comment]
Thanks. Now I get:
Last login: Fri Feb  2 21:05:29 on ttys000
steveparry@Julay1 ~ % qlmanage -p -o /tmp /Users/steveparry/Downloads/Mark\ Cousins\,\ Kevin\ Macdonald\ -\ Imagining\ Reality_\ The\ Faber\ Book\ of\ Documentary\ \(2011\).mobi
Testing Quick Look preview with files:
	/Users/steveparry/Downloads/Mark Cousins, Kevin Macdonald - Imagining Reality_ The Faber Book of Documentary (2011).mobi
* /Users/steveparry/Downloads/Mark Cousins, Kevin Macdonald - Imagining Reality_ The Faber Book of Documentary (2011).mobi did not produce any preview
steveparry@Julay1 ~ %

**Comment by bfabiszewski** [comment]
Difficult to say anything from this output. Especially that they removed `-d` option which gave more debugging info.
May be some problem related to M1. I don't have access to M1 Mac to test. 
But it also can be something else. Maybe the plugin is not installed correctly or does not have proper permissions granted. It is tricky to set it up as it is not bundled with any official App Store application.

**Comment by steveparry1** [comment]
Thank you for trying.

**Comment by bfabiszewski** [comment]
Would be helpful to hear from other M1 users who tried or managed to use this plugin.
Technically it should work as I compiled it also for this CPU.

**Comment by aik099** [comment]
@bfabiszewski,

Initially, I've got this warning with no way to proceed any further:

![2024-02-06_16-18-24](https://github.com/bfabiszewski/QLMobi/assets/1277526/b2bb1d49-416c-42e1-8ba1-7e344916a2fa)

After running `qlmanage -p -o /tmp <path_to_my_mobi_file>` command I got a confirmation dialog (I never saw it again and I forgot to screen capture it), that asked if I was certain, that I wanted to run QlMobi QuickLook generator. Once I've confirmed, then it generated a preview and regular quicklook attempts (when you press a space on a mobi file) also started to work.

@steveparry1 , please:

1. provide a link for downloading a mobi file in question
2. does the issue happen on every mobi file you've tried or just a particular one?

**Comment by bfabiszewski** [comment]
@aik099 Thanks for the info!

Newer macos versions are more problematic towards unofficial apps (not signed). 
Quicklook plugins are also now meant to be distributed with applications, not standalone. 
This creates problems that may be hard to debug.
You probably need to do what I mention in README:
`xattr -d -r com.apple.quarantine ~/Library/QuickLook/QLMobi.qlgenerator`
This will strip quarantine attribute from the plugin.
It may also be necessary to add gatekeeper exception:
`sudo spctl --add ~/Library/QuickLook/QLMobi.qlgenerator`

I can confirm the plugin works on Sonoma, but I did not check on Apple Silicon cpus.

**Comment by steveparry1** [comment]
Here is a link to a .mobi file: https://www.dropbox.com/scl/fi/8tb03erso8lbqep3vhc8i/Alice-in-Wonderland.mobi?rlkey=fvd9gnyuevdbwm1409vd09k9k&dl=0   The issue occurs on every .mobi file I try to preview.

**Comment by aik099** [comment]
> Here is a link to a .mobi file: https://www.dropbox.com/scl/fi/8tb03erso8lbqep3vhc8i/Alice-in-Wonderland.mobi?rlkey=fvd9gnyuevdbwm1409vd09k9k&dl=0 The issue occurs on every .mobi file I try to preview.

It worked for me. Big grey rectangle instead of the book's front cover, but if you scroll down it looks perfect:
![2024-02-09_14-06-40](https://github.com/bfabiszewski/QLMobi/assets/1277526/4895ab81-fcc6-4895-9331-676fd7113b6a)

**Comment by aidan-gibson** [comment]
Worked seamlessly for me on 14.6.1 using brew. This issue should be closed.

**Comment by steveparry1** [comment]
I just upgraded to Sequoia and still no luck previewing .mobi files.  Worse than that I now find none of my epub files preview other than showing the cover! I've given up on mobi. But how do I get my epubs to preview like they did previously? Thanks.

**Comment by bfabiszewski** [comment]
Sequoia changelog says:
> Support for deprecated Quick Look Generator plugins is being removed. To provide previews and thumbnails for your custom file types, migrate to Quick Look Preview Extension and Thumbnail Extension API. (116791365)

I will have to investigate if it is still possible to make standalone Quicklook plugins.
